# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  NugetApiKey:
    secure: gXD4c5l8xUJRlQt5oqbMauiSY6vSlAQ9y8hyR2FO10jTl+nwkAR/SEOLxxLPbN+o

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
#skip_commits:
#message: /updated readme.*|update readme.*s/

skip_commits:
  message: Created.*\.(png|jpg|jpeg|bmp|gif)

only_commits:
  message: /!deploy/

build: false

#Kick off the CI/CD pipeline
test_script:
- ps: . .\build.ps1